channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - typer~=0.6.1
  - biopython~=1.79
  - polars~=0.14.0
  - attrs~=22.1.0
  - pyarrow~=9.0.0
  - cattrs
  - mappy~=2.24
  - pip
  - pip:
    - pysam~=0.20.0  # TODO: make this conda dep when it hits bioconda
platforms:
  - linux-64
  # - osx-64 blocked on pairtools https://github.com/open2c/pairtools/issues/151
  # - osx-arm64  needs bioconda  to support
