[envs.default]
dependencies = [
    "pytest<8.0.0,>=7.1.2",
    "pytest-xdist<3.0.0,>=2.5.0",
    "pytest-cov>=3.0.0",
]

[envs.default.scripts]
test = "pytest {args}"
cli = "pore-c2 {args}"
cov = ["coverage run --module pytest", "coverage report --show-missing"]

[envs.integration]
dependencies = [
    "snakemake>=7.14.0",
    "pytest-workflow>=1.6.0",
    "conda-lock"
]

[envs.integration.scripts]
test = "pytest -c tests/workflow/pytest.ini  tests/workflow/"
lock = "conda-lock -f pyproject.toml -p linux-64 --micromamba --kind explicit"
create = "conda create --name porec2_dev --file conda-linux-64.lock"
update = "conda install --name porec2_dev --file conda-linux-64.lock"



[envs.jupyter]
dependencies = [
  "jupyterlab>=3.4.5",
  "jupyterlab-code-formatter>=1.5.3",
  "jupyterlab-lsp>=3.10.1",
  "jupytext>=1.14.1",
  "line-profiler>=3.5.1",
  "memory-profiler>=0.60.0",
  "black>=22.6.0",
  "isort>=5.10.1",
  "ipython",
  "python-lsp-server[all]"
]

[envs.jupyter.scripts]
lab = "jupyter lab"
