[envs.default]
dependencies = [
    "pytest<8.0.0,>=7.1.2",
    "pytest-xdist<3.0.0,>=2.5.0",
    "pytest-cov>=3.0.0",
]

[envs.default.scripts]
test = "pytest {args}"
cli = "pore-c2 {args}"
cov = ["coverage run --module pytest", "coverage report --show-missing"]

[envs.integration]
dependencies = [
    "snakemake>=7.14.0",
    "pytest-workflow>=1.6.0",
]
post-install-commands = [
  "pip install pysam numpy cython --no-cache-dir",
  "pip install pairtools --no-cache-dir",
]

[envs.integration.scripts]
test = "pytest -c tests/workflow/pytest.ini  tests/workflow/"


[envs.jupyter]
dependencies = [
  "jupyterlab>=3.4.5",
  "jupyterlab-code-formatter>=1.5.3",
  "jupyterlab-lsp>=3.10.1",
  "jupytext>=1.14.1",
  "line-profiler>=3.5.1",
  "memory-profiler>=0.60.0",
  "black>=22.6.0",
  "isort>=5.10.1",
]

[envs.jupyter.scripts]
lab = "jupyter lab"
