# this doesn't work
# {% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - biopython >=1.79
    - pyarrow >=11.0.0
    - pysam >=0.20.0

test:
  imports:
    - pore_c_py

about:
  home: "https://github.com/epi2me-labs/pore-c-py"
  license: Mozilla Public License 2.0 
  license_family: OTHER
  license_file: LICENSE.md
  summary: "Python scripts for working with Pore-C data"
  doc_url: https://github.com/epi2me-labs/pore-c-py
  dev_url: https://github.com/epi2me-labs/pore-c-py

extra:
  recipe-maintainers:
    - epi2melabs-bot

