# this doesn't work
# {% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - minimap2 >=2.24
    - pairtools>=1.0.1
    - cooler >0.8.0
    - samtools
    - whatshap >=1.6
    - hapcut2 ~=1.3.3

test:
  imports:
    - pore_c_py

about:
  home: "https://github.com/epi2me-labs/pore-c-py"
  license: Mozilla Public License 2.0 
  license_family: OTHER
  license_file: LICENSE.md
  summary: "Python scripts for working with Pore-C data"
  doc_url: https://github.com/epi2me-labs/pore-c-py
  dev_url: https://github.com/epi2me-labs/pore-c-py

extra:
  recipe-maintainers:
    - epi2melabs-bot

